import jsPDF from 'jspdf';

export interface PDFMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp?: Date;
}

export interface PDFGenerationOptions {
  title?: string;
  includeTimestamp?: boolean;
  includeCitations?: boolean;
}

/**
 * Generates a PDF from chat messages
 * Implements clean, professional formatting for biomedical research reports
 */
export async function generateChatPDF(
  messages: PDFMessage[],
  options: PDFGenerationOptions = {}
): Promise<void> {
  const {
    title = 'Bio Research Report',
    includeTimestamp = true,
    includeCitations = true,
  } = options;

  // Create PDF with A4 dimensions
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;

  let yPosition = margin;

  // Helper function to add new page if needed
  const checkAndAddPage = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Helper function to wrap text
  const wrapText = (text: string, maxWidth: number): string[] => {
    return pdf.splitTextToSize(text, maxWidth);
  };

  // Add header/title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(31, 41, 55); // gray-800
  pdf.text(title, margin, yPosition);
  yPosition += 12;

  // Add generation date
  if (includeTimestamp) {
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(107, 114, 128); // gray-500
    pdf.text(
      `Generated: ${new Date().toLocaleString()}`,
      margin,
      yPosition
    );
    yPosition += 10;
  }

  // Add separator line
  pdf.setDrawColor(229, 231, 235); // gray-200
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Process each message
  for (let i = 0; i < messages.length; i++) {
    const message = messages[i];

    checkAndAddPage(20);

    // Message header
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');

    if (message.role === 'user') {
      pdf.setTextColor(59, 130, 246); // blue-500
      pdf.text('You:', margin, yPosition);
    } else {
      pdf.setTextColor(139, 92, 246); // purple-500
      pdf.text('AI Assistant:', margin, yPosition);
    }

    yPosition += 8;

    // Message content
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(55, 65, 81); // gray-700

    // Clean and process the content
    const cleanContent = cleanMarkdownForPDF(message.content);
    const contentLines = wrapText(cleanContent, maxWidth);

    // Add content with proper spacing
    for (const line of contentLines) {
      checkAndAddPage(7);
      pdf.text(line, margin, yPosition);
      yPosition += 6;
    }

    yPosition += 8; // Space between messages

    // Add light separator between messages (except for last)
    if (i < messages.length - 1) {
      checkAndAddPage(5);
      pdf.setDrawColor(243, 244, 246); // gray-100
      pdf.setLineWidth(0.2);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;
    }
  }

  // Add footer to all pages
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);

    // Footer line
    pdf.setDrawColor(229, 231, 235);
    pdf.setLineWidth(0.3);
    pdf.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);

    // Footer text
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(156, 163, 175); // gray-400

    // Left side - branding
    pdf.text('Generated by Bio AI', margin, pageHeight - 10);

    // Right side - page numbers
    pdf.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - margin - 20,
      pageHeight - 10
    );
  }

  // Generate filename with timestamp
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `biomed-research-${timestamp}.pdf`;

  // Download the PDF
  pdf.save(filename);
}

/**
 * Cleans markdown formatting for PDF output
 * Removes markdown syntax while preserving readability
 */
function cleanMarkdownForPDF(text: string): string {
  let cleaned = text;

  // Remove markdown headers
  cleaned = cleaned.replace(/^#{1,6}\s+/gm, '');

  // Remove bold/italic markers
  cleaned = cleaned.replace(/\*\*([^*]+)\*\*/g, '$1');
  cleaned = cleaned.replace(/\*([^*]+)\*/g, '$1');
  cleaned = cleaned.replace(/__([^_]+)__/g, '$1');
  cleaned = cleaned.replace(/_([^_]+)_/g, '$1');

  // Convert links to readable format
  cleaned = cleaned.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1 ($2)');

  // Remove code block markers but keep content
  cleaned = cleaned.replace(/```[\w]*\n/g, '\n');
  cleaned = cleaned.replace(/```/g, '');

  // Convert inline code
  cleaned = cleaned.replace(/`([^`]+)`/g, '$1');

  // Remove citation markers (keep numbers but remove brackets)
  cleaned = cleaned.replace(/\[(\d+)\]/g, '($1)');

  // Clean up excessive newlines
  cleaned = cleaned.replace(/\n{3,}/g, '\n\n');

  // Trim
  cleaned = cleaned.trim();

  return cleaned;
}

/**
 * Extracts text content from message parts for PDF generation
 */
export function extractTextFromMessageParts(parts: any[]): string {
  return parts
    .filter((part) => part.type === 'text')
    .map((part) => part.text)
    .join('\n\n');
}
